import { StyleSheet } from 'react-native';
import { theme } from '../../../global/themas';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  mainContent: {
    paddingBottom: 20,
    flex: 1,
  },
  content: {
    padding: 20,
    marginTop: 10,
  },
  cardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  card: {
    backgroundColor: '#fff',
    width: '48%',
    padding: 15,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardLabel: {
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 12,
    color: theme.colors.textLight,
  },
  cardValue: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 18,
    color: theme.colors.primary,
    marginTop: 5,
  },
  titleContainer: {
    paddingHorizontal: 20,
    marginTop: 10,
    marginBottom: 20,
  },
  titleLine: {
    fontSize: 48,
    fontFamily: theme.fonts.headingBold,
    color: theme.colors.textPrimary,
    lineHeight: 50,
    textTransform: 'uppercase',
  },
  titleHighlight: {
    color: theme.colors.primary,
  },
  description: {
    paddingHorizontal: 20,
    fontSize: 16,
    fontFamily: theme.fonts.bodyRegular,
    color: theme.colors.textBrown,
    lineHeight: 24,
    marginTop: 5,
    marginBottom: 30,
  },
  inputContainer: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  inputLabel: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 14,
    color: theme.colors.textBrown,
    marginBottom: 8,
  },
  inputValue: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 22,
    color: theme.colors.textSecondary,
  },
  inputObservation: {
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 10,
    color: theme.colors.primary,
    marginTop: 6,
    textTransform: 'uppercase',
  },
  genderContainer: {
    paddingHorizontal: 20,
    marginTop: 10,
    marginBottom: 30,
  },
  genderRow: {
    flexDirection: 'row',
    gap: 15,
    marginTop: 10,
  },
  genderButton: {
    flex: 1,
    height: 55,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  genderButtonSelected: {
    borderColor: theme.colors.primary,
    borderWidth: 2,
  },
  genderText: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 14,
    color: theme.colors.textLight,
  },
  genderTextSelected: {
    color: theme.colors.primary,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingRight: 10,
    marginBottom: 20,
  },
  sectionTitle: {
    fontFamily: theme.fonts.headingBold,
    fontSize: 20,
    color: theme.colors.textPrimary,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#fff',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  editText: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 12,
    color: theme.colors.primary,
  },
  inputBox: {
    height: 65,
    borderRadius: 8,
    borderWidth: 1.5,
    overflow: 'hidden',
  },
  inputElement: {
    flex: 1,
    paddingHorizontal: 15,
    fontFamily: theme.fonts.bodyBold,
    fontSize: 26,
  },
  inputLocked: {
    backgroundColor: '#F0F0F0',
    borderColor: '#E0E0E0',
    color: '#666',
  },
  inputUnlocked: {
    backgroundColor: '#FFF',
    borderColor: theme.colors.primary,
    color: theme.colors.textPrimary,
  },
  photoSection: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 30,
    gap: 20,
  },
  photoContainer: {
    position: 'relative',
    width: 80,
    height: 80,
  },
  profilePhoto: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#E0E0E0',
    borderWidth: 2,
    borderColor: theme.colors.primary,
  },
  changePhotoButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: theme.colors.primary,
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: theme.colors.background,
  },
  photoTextContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  photoTitle: {
    fontFamily: theme.fonts.headingBold,
    fontSize: 18,
    color: theme.colors.textPrimary,
    textTransform: 'uppercase',
  },
  photoSubtitle: {
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 12,
    color: theme.colors.textBrown,
    marginTop: 2,
  },
  nameInput: {
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.primary,
    paddingBottom: 2,
    minWidth: 150,
  },
  professionalContainer: {
    paddingHorizontal: 20,
    marginTop: 15,
    gap: 15,
  },
  infoCard: {
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 15,
  },
  infoLabel: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 12,
    color: theme.colors.textBrown,
    marginBottom: 4,
  },
  infoValue: {
    fontFamily: theme.fonts.headingBold,
    fontSize: 18,
    color: theme.colors.textPrimary,
    textTransform: 'uppercase',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 40,
    gap: 10,
    paddingVertical: 15,
  },
  logoutText: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 14,
    color: theme.colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
});