// src/app/index.styles.ts
import { StyleSheet } from 'react-native';
import { theme } from '../global/themas';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#3D0D14', 
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%', // Garante que a imagem cubra tudo
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'space-between',
  },
  headerSection: {
    paddingHorizontal: 32,
    paddingTop: 80,
    paddingBottom: 40,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 40,
  },
  logoText: {
    color: '#FFF',
    fontFamily: theme.fonts.bodyMedium,
    fontSize: 14,
    letterSpacing: 2,
    marginLeft: 8,
  },
  mainTitle: {
    color: '#FFF',
    fontFamily: theme.fonts.headingBold,
    fontSize: 40,
    lineHeight: 44,
  },
  subTitleHighlight: {
    color: '#D90429',
    fontFamily: theme.fonts.headingBold,
    fontSize: 40,
    lineHeight: 44,
    marginBottom: 16,
  },
  description: {
    color: '#E0E0E0',
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 40,
  },
  partnerContainer: {
    marginTop: 20,
  },
  partnerLabel: {
    color: '#A0A0A0',
    fontFamily: theme.fonts.bodyMedium,
    fontSize: 10,
    letterSpacing: 1,
    marginBottom: 4,
  },
  partnerName: {
    color: theme.colors.critical, 
    fontFamily: theme.fonts.headingBold,
    fontSize: 24,
    lineHeight: 26,
  },
  bottomCard: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingHorizontal: 32,
    paddingTop: 40,
    paddingBottom: 50,
  },
  cardTitle: {
    color: theme.colors.critical,
    fontFamily: theme.fonts.headingBold,
    fontSize: 26,
    letterSpacing: 1,
    marginBottom: 8,
  },
  cardSubtitle: {
    color: '#7C7C8A',
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 14,
    marginBottom: 32,
  },
  inputLabel: {
    color: '#7C7C8A',
    fontFamily: theme.fonts.bodyBold,
    fontSize: 10,
    letterSpacing: 1,
    marginBottom: 8,
    marginTop: 16,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.textWhite, 
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    paddingHorizontal: 16,
    height: 56,
  },
  input: {
    flex: 1,
    color: '#FFF',
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 16,
  },
  optionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 32,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkbox: {
    borderRadius: 4,
    width: 18,
    height: 18,
    marginRight: 8,
  },
  checkboxLabel: {
    color: '#7C7C8A',
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 14,
  },
  forgotPassword: {
    color: '#D90429',
    fontFamily: theme.fonts.bodyBold,
    fontSize: 12,
  },
  loginButton: {
    height: 56,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E4E4E7',
    backgroundColor: theme.colors.critical,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 32,
  },
  loginButtonText: {
    color: theme.colors.textWhite,
    fontFamily: theme.fonts.bodyBold,
    fontSize: 14,
    letterSpacing: 1,
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 32,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E4E4E7',
  },
  dividerText: {
    color: '#C4C4CC',
    fontFamily: theme.fonts.bodyMedium,
    fontSize: 12,
    marginHorizontal: 16,
  },
  socialRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 40,
  },
  socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 48,
    flex: 0.48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E4E4E7',
  },
  socialButtonText: {
    color: theme.colors.textSecondary,
    fontFamily: theme.fonts.bodyMedium,
    fontSize: 14,
    marginLeft: 8,
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  footerText: {
    color: '#7C7C8A',
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 14,
  },
  footerLink: {
    color: '#6E111E',
    fontFamily: theme.fonts.bodyBold,
    fontSize: 14,
  },
});